import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { audioQueueErrorMessage, audioQueueJobMarkup, canListenToAudioJob, createAudioQueueUI } from "../src/audio-queue-ui.js";
import { audioControlsMarkup } from "../src/voice-ui.js";
import translations from "../src/locales/audio-queue.js";
import { setLocale, t } from "../src/i18n.js";

const makeJob = (id, status = "queued") => ({ id, bookId: id, title: `Book ${id}`, voice: { id: "ff_siwis", name: "Siwis" }, status, progress: .25, completedSegments: 5, totalSegments: 20, completedChapters: 1, totalChapters: 4, audioBytes: 5_000_000 });
let queue, ui, snapshot, onListen, onBrowse, changed, originalScrollIntoView;
const settled = () => vi.waitFor(() => expect(document.querySelector("[data-audio-queue-list]").getAttribute("aria-busy")).toBe("false"));
const action = (id, verb) => document.querySelector(`[data-audio-job="${id}"] [data-audio-queue-action="${verb}"]`);
beforeEach(() => {
  setLocale("fr");
  Object.defineProperty(HTMLDialogElement.prototype, "showModal", { configurable: true, value() { this.setAttribute("open", ""); } });
  Object.defineProperty(HTMLDialogElement.prototype, "close", { configurable: true, value() { this.removeAttribute("open"); this.dispatchEvent(new Event("close")); } });
  originalScrollIntoView = Object.getOwnPropertyDescriptor(Element.prototype, "scrollIntoView");
  Object.defineProperty(Element.prototype, "scrollIntoView", { configurable: true, value: vi.fn() });
  document.body.innerHTML = '<button id="queue-trigger">Audio</button>';
  document.getElementById("queue-trigger").focus();
  snapshot = { jobs: [], activeJobId: null, suspended: [] };
  queue = {
    snapshot: vi.fn(() => snapshot), list: vi.fn(async () => snapshot),
    subscribe: vi.fn(listener => { changed = listener; return vi.fn(); }),
    pause: vi.fn(async id => { snapshot.jobs.find(job => job.id === id).status = "paused"; changed(snapshot); }),
    resume: vi.fn(async id => { snapshot.jobs.find(job => job.id === id).status = "queued"; changed(snapshot); }),
    cancel: vi.fn(async id => { snapshot.jobs = snapshot.jobs.filter(job => job.id !== id); changed(snapshot); }),
    remove: vi.fn(async id => { snapshot.jobs = snapshot.jobs.filter(job => job.id !== id); changed(snapshot); }),
    clearAll: vi.fn(async () => { snapshot.jobs = []; changed(snapshot); }),
  };
  onListen = vi.fn();
  onBrowse = vi.fn();
  ui = createAudioQueueUI({ queue, onListen, onBrowse });
});
afterEach(() => {
  ui.dispose(); setLocale("fr"); document.body.innerHTML = "";
  delete HTMLDialogElement.prototype.showModal; delete HTMLDialogElement.prototype.close;
  if (originalScrollIntoView) Object.defineProperty(Element.prototype, "scrollIntoView", originalScrollIntoView);
  else delete Element.prototype.scrollIntoView;
});

describe("local audio queue dialog", () => {
  it("shows actual generated bytes and keeps the clear control stable as preparation progresses", async () => {
    snapshot.jobs = [makeJob("ready", "ready"), { ...makeJob("pending", "queued"), audioBytes: 0 }];
    ui.open(); await settled();
    expect(document.querySelector("[data-audio-queue-size]").textContent).toBe("Audio généré : 5 Mo");
    const clear = document.querySelector("[data-audio-queue-clear]");
    clear.focus();
    snapshot.jobs[1].audioBytes = 2_000_000;
    changed(snapshot);
    expect(document.querySelector("[data-audio-queue-size]").textContent).toBe("Audio généré : 7 Mo");
    expect(document.querySelector("[data-audio-queue-clear]")).toBe(clear);
    expect(document.activeElement).toBe(clear);
    expect(queue.clearAll).not.toHaveBeenCalled();
  });

  it("requires confirmation and lets Escape cancel without deleting or closing the queue", async () => {
    snapshot.jobs = [makeJob("ready", "ready")];
    ui.open(); await settled();
    const clear = document.querySelector("[data-audio-queue-clear]");
    clear.click();
    expect(document.querySelector("[data-audio-queue-clear-confirmation]").hidden).toBe(false);
    expect(document.querySelector("[data-audio-queue-clear-confirmation]").textContent).toContain("Vos livres et les voix téléchargées seront conservés");
    expect(document.activeElement).toBe(document.querySelector("[data-audio-queue-clear-cancel]"));
    document.querySelector("dialog").dispatchEvent(new Event("cancel", { cancelable: true }));
    expect(document.querySelector("[data-audio-queue-clear-confirmation]").hidden).toBe(true);
    expect(document.activeElement).toBe(clear);
    expect(queue.clearAll).not.toHaveBeenCalled();
    clear.click();
    document.querySelector("[data-audio-queue-clear-cancel]").click();
    expect(document.activeElement).toBe(clear);
    expect(snapshot.jobs).toHaveLength(1);
  });

  it("clears once and blocks conflicting actions until storage deletion completes", async () => {
    snapshot.jobs = [makeJob("ready", "ready"), makeJob("active", "preparing")];
    let finish;
    queue.clearAll.mockImplementation(() => new Promise(resolve => { finish = () => { snapshot.jobs = []; changed(snapshot); resolve(); }; }));
    ui.open(); await settled();
    document.querySelector("[data-audio-queue-clear]").click();
    const confirm = document.querySelector("[data-audio-queue-clear-confirm]");
    confirm.click(); confirm.click();
    expect(queue.clearAll).toHaveBeenCalledTimes(1);
    expect(document.querySelector("[data-audio-queue-storage]").getAttribute("aria-busy")).toBe("true");
    expect(document.querySelector("[data-audio-queue-clearing]").hidden).toBe(false);
    expect(document.querySelector("[data-audio-queue-close]").disabled).toBe(true);
    document.querySelector("[data-audio-queue-browse]").click();
    action("active", "cancel").click();
    action("ready", "listen").click();
    document.querySelector("dialog").dispatchEvent(new Event("cancel", { cancelable: true }));
    expect(queue.cancel).not.toHaveBeenCalled();
    expect(onListen).not.toHaveBeenCalled();
    expect(onBrowse).not.toHaveBeenCalled();
    expect(document.querySelector("dialog")).not.toBeNull();
    finish();
    await vi.waitFor(() => expect(document.querySelectorAll("[data-audio-job]")).toHaveLength(0));
    expect(document.querySelector("[data-audio-queue-size]").textContent).toBe("Audio généré : 0 Mo");
    expect(document.querySelector("[data-audio-queue-clear]").disabled).toBe(true);
    expect(document.querySelector("[data-audio-queue-notice]").textContent).toContain("Vos livres et vos voix sont conservés");
    expect(document.querySelector("[data-audio-queue-notice]").dataset.error).toBe("false");
    expect(document.activeElement).toBe(document.querySelector("[data-audio-queue-close]"));
  });

  it("keeps failed deletion retryable without reporting success or losing current progress", async () => {
    snapshot.jobs = [makeJob("ready", "ready")];
    queue.clearAll.mockRejectedValueOnce(new Error("storage unavailable"));
    ui.open(); await settled();
    document.querySelector("[data-audio-queue-clear]").click();
    document.querySelector("[data-audio-queue-clear-confirm]").click();
    await vi.waitFor(() => expect(document.querySelector("[data-audio-queue-notice]").textContent).toContain("Impossible de supprimer"));
    expect(document.querySelectorAll("[data-audio-job]")).toHaveLength(1);
    expect(document.querySelector("[data-audio-queue-clear-confirmation]").hidden).toBe(false);
    expect(document.querySelector("[data-audio-queue-clear-confirm]").disabled).toBe(false);
    expect(document.activeElement).toBe(document.querySelector("[data-audio-queue-clear-cancel]"));
    document.querySelector("[data-audio-queue-clear-confirm]").click();
    await vi.waitFor(() => expect(document.querySelectorAll("[data-audio-job]")).toHaveLength(0));
    expect(queue.clearAll).toHaveBeenCalledTimes(2);
  });

  it("localizes cleanup and its confirmation in every interface language without moving focus", async () => {
    snapshot.jobs = [makeJob("ready", "ready")];
    ui.open(); await settled();
    document.querySelector("[data-audio-queue-clear]").click();
    const cancel = document.querySelector("[data-audio-queue-clear-cancel]");
    for (const language of ["fr", "en", "es", "it", "de", "pt"]) {
      setLocale(language);
      window.dispatchEvent(new Event("languagechange"));
      expect(document.querySelector("#audio-queue-storage-title").textContent).toBe(t("Espace audio"));
      expect(document.querySelector("[data-audio-queue-clear-confirm]").textContent).toBe(t("Supprimer tous les audios"));
      expect(document.querySelector("[data-audio-queue-size]").textContent).toContain(t("Audio généré : {size}", { size: "" }));
      expect(document.activeElement).toBe(cancel);
    }
  });

  it("keeps retired partial audio playable and replaces Resume with an explicit new-voice choice", async () => {
    const onChooseVoice = vi.fn();
    ui.dispose();
    ui = createAudioQueueUI({ queue, onListen, onChooseVoice });
    snapshot.jobs = [{ ...makeJob("old", "unavailable"), canPrepare: false, canListen: true }];
    ui.open(); await settled();
    expect(action("old", "listen")).not.toBeNull();
    expect(action("old", "resume")).toBeNull();
    expect(action("old", "pause")).toBeNull();
    expect(action("old", "choose-voice").textContent).toContain("nouvelle voix");
    expect(document.querySelector(".audio-job-partial").textContent).toContain("passages enregistrés restent disponibles");
    action("old", "listen").click();
    expect(onListen).toHaveBeenCalledWith(snapshot.jobs[0], { fromStart: true });
    ui.open(); await settled();
    action("old", "choose-voice").click();
    expect(onChooseVoice).toHaveBeenCalledWith(snapshot.jobs[0]);
    expect(queue.resume).not.toHaveBeenCalled();
    expect(queue.remove).not.toHaveBeenCalled();
    expect(queue.cancel).not.toHaveBeenCalled();
  });

  it("explains the end of retired partial audio without promising more generation", () => {
    document.body.innerHTML = audioControlsMarkup({ status: "buffering", prepared: true, preparationStatus: "unavailable" });
    expect(document.querySelector('[role="status"]').textContent).toContain("Fin des passages enregistrés");
    expect(document.querySelector('[data-voice-action="queue"]')).not.toBeNull();
    expect(audioQueueErrorMessage({ code: "VOICE_RETIRED" })).toContain("nouvelle voix");
  });

  it("keeps rows, buttons and their pointer targets connected across progress updates", async () => {
    const job = { ...makeJob("a", "preparing"), canListen: false, completedSegments: 0, progress: 0 };
    snapshot.jobs = [job, makeJob("b", "paused")];
    ui.open();
    await settled();
    const row = document.querySelector('[data-audio-job="a"]');
    const status = row.querySelector(".audio-job-status");
    const cancel = action("a", "cancel");
    const label = cancel.lastElementChild;
    const otherRow = document.querySelector('[data-audio-job="b"]');
    const dialog = document.querySelector("dialog");
    dialog.scrollTop = 120;
    cancel.focus();
    label.dispatchEvent(new Event("pointerdown", { bubbles: true }));
    const disconnected = [];
    const observer = new MutationObserver(records => {
      for (const record of records) for (const removed of record.removedNodes) {
        if ([row, cancel, label].some(target => removed === target || removed.contains?.(target))) disconnected.push(removed);
      }
    });
    observer.observe(dialog, { childList: true, subtree: true });
    for (let completed = 1; completed <= 4; completed++) {
      Object.assign(job, { completedSegments: completed, readySegments: completed, canListen: true, progress: completed / 20, audioBytes: completed * 100 });
      changed(snapshot);
      expect(document.querySelector('[data-audio-job="a"]')).toBe(row);
      expect(action("a", "cancel")).toBe(cancel);
      expect(cancel.lastElementChild).toBe(label);
      expect(row.querySelector(".audio-job-status")).toBe(status);
      expect(document.querySelector('[data-audio-job="b"]')).toBe(otherRow);
      expect(document.activeElement).toBe(cancel);
      expect(dialog.scrollTop).toBe(120);
    }
    await Promise.resolve();
    observer.disconnect();
    expect(disconnected).toEqual([]);
    expect(row.querySelector("progress").value).toBe(20);
    expect(row.textContent).toContain("4 sur 20 passages");
    label.dispatchEvent(new Event("pointerup", { bubbles: true }));
    label.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    await vi.waitFor(() => expect(queue.cancel).toHaveBeenCalledExactlyOnceWith("a"));
    expect(row.isConnected).toBe(false);
    expect(otherRow.isConnected).toBe(true);
  });

  it("preserves a held cancel target when completion changes it to Delete audio", async () => {
    const job = makeJob("a", "preparing");
    snapshot.jobs = [job];
    ui.open();
    await settled();
    const cancel = action("a", "cancel");
    const label = cancel.lastElementChild;
    cancel.focus();
    label.dispatchEvent(new Event("pointerdown", { bubbles: true }));
    const observer = new MutationObserver(() => {});
    observer.observe(document.querySelector("dialog"), { childList: true, subtree: true });
    Object.assign(job, { status: "ready", progress: 1, completedSegments: 20 });
    changed(snapshot);
    expect(action("a", "remove")).toBe(cancel);
    expect(cancel.lastElementChild).toBe(label);
    expect(label.textContent).toBe("Supprimer l’audio");
    expect(document.activeElement).toBe(cancel);
    expect(action("a", "pause")).toBeNull();
    const removed = observer.takeRecords().flatMap(record => [...record.removedNodes]);
    observer.disconnect();
    expect(removed.some(node => [cancel, label].some(target => node === target || node.contains?.(target)))).toBe(false);
    label.dispatchEvent(new Event("pointerup", { bubbles: true }));
    label.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    await vi.waitFor(() => expect(queue.remove).toHaveBeenCalledExactlyOnceWith("a"));
    expect(document.querySelector('[data-audio-job="a"]')).toBeNull();
  });

  it("updates pause, errors and language without replacing the same action controls", async () => {
    const job = makeJob("a", "preparing");
    snapshot.jobs = [job];
    ui.open();
    await settled();
    const pause = action("a", "pause");
    const label = pause.lastElementChild;
    pause.focus();
    Object.assign(job, { status: "error", error: { code: "STORAGE_FULL" } });
    changed(snapshot);
    expect(action("a", "resume")).toBe(pause);
    expect(pause.lastElementChild).toBe(label);
    expect(label.textContent).toBe("Réessayer");
    expect(document.querySelector(".audio-job-error").textContent).toContain("stockage");
    job.status = "paused"; job.error = null;
    setLocale("en");
    window.dispatchEvent(new Event("languagechange"));
    expect(action("a", "resume")).toBe(pause);
    expect(pause.lastElementChild).toBe(label);
    expect(label.textContent).toBe("Resume");
    expect(document.querySelector(".audio-job-error")).toBeNull();
    expect(document.activeElement).toBe(pause);
  });

  it("does not let a delayed native close event dismiss a newly reopened queue", async () => {
    Object.defineProperty(HTMLDialogElement.prototype, "close", { configurable: true, value() { this.removeAttribute("open"); } });
    snapshot.jobs = [makeJob("a"), makeJob("b")];
    ui.open({ bookId: "a" });
    await settled();
    const previousDialog = document.querySelector("dialog");
    ui.close();
    ui.open({ bookId: "b" });
    await settled();
    previousDialog.dispatchEvent(new Event("close"));
    expect(document.querySelector("dialog").open).toBe(true);
    expect(document.activeElement).toBe(action("b", "listen"));
  });

  it("highlights every preparation for the requested book while keeping the whole queue visible", async () => {
    snapshot.jobs = [makeJob("a", "preparing"), makeJob("b", "ready"), { ...makeJob("b-second"), bookId: "b" }];
    ui.open({ bookId: "b" });
    await settled();
    expect(document.querySelectorAll(".audio-queue-job")).toHaveLength(3);
    expect(document.querySelectorAll(".audio-queue-job.is-current-book")).toHaveLength(2);
    expect(document.activeElement).toBe(action("b", "listen"));
    expect(Element.prototype.scrollIntoView).toHaveBeenCalledTimes(2);
    expect(queue.pause).not.toHaveBeenCalled();
    snapshot.jobs[1].audioBytes += 100;
    changed(snapshot);
    expect(document.activeElement).toBe(action("b", "listen"));
    expect(Element.prototype.scrollIntoView).toHaveBeenCalledTimes(2);
  });

  it("focuses the status before audio is ready and can target another book in an open dialog", async () => {
    snapshot.jobs = [{ ...makeJob("a", "preparing"), canListen: false }, { ...makeJob("b", "paused"), canListen: false }];
    ui.open({ bookId: "a" });
    await settled();
    const status = document.querySelector('[data-audio-job="a"] .audio-job-status');
    expect(document.activeElement).toBe(status);
    expect(status.textContent).toContain("Book a");
    expect(status.textContent).toContain("Préparation en cours");
    changed(snapshot);
    expect(document.activeElement.matches('.audio-job-status')).toBe(true);
    ui.open({ bookId: "b" });
    expect(document.activeElement).toBe(action("b", "resume"));
    expect(document.querySelector('[data-audio-job="a"]').classList.contains("is-current-book")).toBe(false);
    ui.open();
    expect(document.querySelectorAll(".is-current-book")).toHaveLength(0);
    expect(document.activeElement).toBe(document.querySelector("[data-audio-queue-close]"));
  });

  it("focuses a matching preparation persisted after opening, unless the user already moved elsewhere", async () => {
    ui.open({ bookId: "late" });
    await settled();
    snapshot.jobs = [{ ...makeJob("late", "preparing"), canListen: false }];
    changed(snapshot);
    expect(document.activeElement).toBe(document.querySelector('[data-audio-job="late"] .audio-job-status'));
    ui.close();
    snapshot.jobs = [];
    ui.open({ bookId: "another" });
    await settled();
    const browse = document.querySelector("[data-audio-queue-browse]");
    browse.focus();
    browse.dispatchEvent(new KeyboardEvent("keydown", { key: "Tab", bubbles: true }));
    snapshot.jobs = [makeJob("another", "preparing")];
    changed(snapshot);
    expect(document.activeElement).toBe(browse);
    expect(document.querySelector('[data-audio-job="another"]').classList.contains("is-current-book")).toBe(true);
  });

  it("offers another voice only with a callback, closes the queue, and preserves existing preparation", async () => {
    const job = makeJob("a", "preparing");
    snapshot.jobs = [job];
    ui.open({ bookId: "a" });
    await settled();
    expect(action("a", "choose-voice")).toBeNull();
    ui.dispose();
    const onChooseVoice = vi.fn();
    ui = createAudioQueueUI({ queue, onChooseVoice });
    ui.open({ bookId: "a" });
    await settled();
    expect(action("a", "choose-voice").textContent).toContain("Préparer avec une autre voix");
    action("a", "choose-voice").click();
    expect(document.querySelector("dialog")).toBeNull();
    expect(onChooseVoice).toHaveBeenCalledWith(job);
    expect(snapshot.jobs).toEqual([job]);
    expect(queue.pause).not.toHaveBeenCalled();
    expect(queue.cancel).not.toHaveBeenCalled();
    expect(queue.remove).not.toHaveBeenCalled();
  });

  it("recovers if opening another voice fails without removing the saved audio", async () => {
    const job = makeJob("a", "ready");
    snapshot.jobs = [job];
    ui.dispose();
    ui = createAudioQueueUI({ queue, onChooseVoice: vi.fn().mockRejectedValue(new Error("missing book")) });
    ui.open({ bookId: "a" });
    await settled();
    action("a", "choose-voice").click();
    await vi.waitFor(() => expect(document.querySelector("[data-audio-queue-notice]")?.textContent).toContain("Réessayez"));
    expect(document.querySelector('[data-audio-job="a"]').classList.contains("is-current-book")).toBe(true);
    expect(queue.remove).not.toHaveBeenCalled();
  });

  it("lets the user browse more books while keeping preparation running", async () => {
    snapshot.jobs = [makeJob("first", "preparing")];
    ui.open();
    await settled();
    expect(document.querySelector(".audio-queue-browse").textContent).toContain("La préparation continue si vous fermez");
    document.querySelector("[data-audio-queue-browse]").click();
    expect(document.querySelector("dialog")).toBeNull();
    expect(onBrowse).toHaveBeenCalledTimes(1);
    expect(queue.pause).not.toHaveBeenCalled();
    expect(queue.cancel).not.toHaveBeenCalled();
    expect(snapshot.jobs[0].status).toBe("preparing");
  });

  it("offers partial listening only once the contiguous beginning is ready", async () => {
    const job = { ...makeJob("first", "preparing"), canListen: false, readySegments: 0 };
    snapshot.jobs = [job];
    ui.open();
    await settled();
    expect(action("first", "listen")).toBeNull();
    job.canListen = true;
    job.readySegments = 1;
    changed(snapshot);
    expect(action("first", "listen").textContent).toContain("Écouter le début");
    expect(action("first", "pause")).not.toBeNull();
    expect(action("first", "cancel")).not.toBeNull();
    expect(document.querySelector(".audio-job-partial").textContent).toContain("Une attente est possible");
    action("first", "listen").click();
    expect(onListen).toHaveBeenCalledWith(job, { fromStart: true });
    expect(queue.pause).not.toHaveBeenCalled();
  });

  it("keeps partial listening available for paused or interrupted preparations", () => {
    for (const status of ["queued", "preparing", "paused", "error"]) {
      const job = { ...makeJob("first", status), canListen: true, readySegments: 1 };
      document.body.innerHTML = audioQueueJobMarkup(job);
      expect(action("first", "listen")).not.toBeNull();
      expect(action("first", "cancel")).not.toBeNull();
      if (["paused", "error"].includes(status)) expect(action("first", "resume")).not.toBeNull();
    }
    expect(canListenToAudioJob({ completedSegments: 3 })).toBe(true);
    expect(canListenToAudioJob({ completedSegments: 3, readySegments: 0 })).toBe(false);
    expect(canListenToAudioJob({ completedSegments: 3, canListen: false })).toBe(false);
  });

  it("explains foreground preparation and starts nothing when empty", async () => {
    ui.open();
    await settled();
    expect(document.querySelector("[data-audio-queue-empty]").hidden).toBe(false);
    expect(document.querySelector("dialog").textContent).toContain("Après fermeture, relancez-la ici");
    expect(queue.resume).not.toHaveBeenCalled();
    expect(onListen).not.toHaveBeenCalled();
    ui.close();
    expect(document.activeElement.id).toBe("queue-trigger");
    expect(queue.pause).not.toHaveBeenCalled();
  });

  it("shows measured progress, storage and ready playback independently", async () => {
    snapshot.jobs = [makeJob("active", "preparing"), { ...makeJob("next"), readySegments: 0 }, makeJob("ready", "ready")];
    ui.open();
    await settled();
    expect(document.querySelector('[data-audio-job="active"] progress').value).toBe(25);
    expect(document.querySelector('[data-audio-job="active"]').textContent).toContain("5 sur 20 passages");
    expect(document.querySelector('[data-audio-job="active"]').textContent).toContain("Audio conservé");
    expect(action("active", "listen").textContent).toContain("Écouter le début");
    expect(action("next", "listen")).toBeNull();
    action("ready", "listen").click();
    expect(onListen).toHaveBeenCalledWith(expect.objectContaining({ id: "ready", status: "ready" }), { fromStart: false });
    expect(document.querySelector("dialog")).toBeNull();
  });

  it("pauses, resumes and removes only the chosen job, preserving focus on progress updates", async () => {
    snapshot.jobs = [makeJob("a", "preparing"), makeJob("b", "ready")];
    ui.open();
    await settled();
    action("a", "pause").focus();
    snapshot.jobs[0].progress = .4;
    changed(snapshot);
    expect(document.activeElement).toBe(action("a", "pause"));
    action("a", "pause").click();
    await vi.waitFor(() => expect(action("a", "resume")).not.toBeNull());
    expect(queue.pause).toHaveBeenCalledWith("a");
    expect(document.activeElement).toBe(action("a", "resume"));
    action("a", "resume").click();
    await vi.waitFor(() => expect(queue.resume).toHaveBeenCalledWith("a"));
    action("b", "remove").click();
    await vi.waitFor(() => expect(document.querySelector('[data-audio-job="b"]')).toBeNull());
    expect(queue.remove).toHaveBeenCalledWith("b");
    expect(document.querySelector('[data-audio-job="a"]')).not.toBeNull();
  });

  it("blocks duplicate actions while persisting and recovers from an action failure", async () => {
    snapshot.jobs = [makeJob("a", "paused")];
    let reject;
    queue.resume.mockImplementationOnce(() => new Promise((resolve, fail) => { reject = fail; }));
    ui.open();
    await settled();
    action("a", "resume").click();
    expect(action("a", "resume").getAttribute("aria-disabled")).toBe("true");
    action("a", "resume").click();
    expect(queue.resume).toHaveBeenCalledTimes(1);
    reject(new Error("storage failed"));
    await vi.waitFor(() => expect(document.querySelector("[data-audio-queue-notice]").textContent).toContain("Réessayez"));
    expect(action("a", "resume").getAttribute("aria-disabled")).toBeNull();
  });

  it("supports cancellation and closes on Escape without pausing other jobs", async () => {
    snapshot.jobs = [makeJob("a"), makeJob("b")];
    ui.open();
    await settled();
    action("a", "cancel").click();
    await vi.waitFor(() => expect(queue.cancel).toHaveBeenCalledWith("a"));
    const unsubscribe = queue.subscribe.mock.results[0].value;
    document.querySelector("dialog").dispatchEvent(new Event("cancel", { cancelable: true }));
    expect(unsubscribe).toHaveBeenCalledTimes(1);
    expect(queue.pause).not.toHaveBeenCalled();
    expect(document.activeElement.id).toBe("queue-trigger");
  });

  it("shows storage recovery and never injects book metadata or errors as HTML", async () => {
    const job = makeJob("a", "error");
    job.title = '<img src=x onerror="alert(1)">';
    job.error = { code: "STORAGE_FULL", message: "private technical details" };
    snapshot.jobs = [job];
    ui.open();
    await settled();
    expect(document.querySelector("dialog img")).toBeNull();
    expect(document.querySelector(".audio-job-error").textContent).toContain("stockage");
    expect(document.querySelector("dialog").textContent).not.toContain("private technical details");
    expect(action("a", "resume").textContent).toContain("Réessayer");
  });

  it("localizes an open queue without changing book titles or losing the selected control", async () => {
    snapshot.jobs = [makeJob("a", "paused")];
    ui.open();
    await settled();
    action("a", "resume").focus();
    setLocale("de");
    window.dispatchEvent(new Event("languagechange"));
    expect(document.querySelector("#audio-queue-title").textContent).toBe("Audio vorbereiten");
    expect(document.querySelector(".audio-job-heading h3").textContent).toBe("Book a");
    expect(document.activeElement).toBe(action("a", "resume"));
    expect(action("a", "resume").textContent).toContain("Fortsetzen");
  });
});

describe("audio queue translations", () => {
  it("explains buffering and links to the queue for each preparation state", () => {
    for (const [state, source] of [
      ["preparing", "Vous avez rejoint la préparation. L’écoute reprend dès que la suite est prête."],
      ["queued", "Ce livre attend son tour. L’écoute reprendra quand la suite sera prête."],
      ["paused", "La préparation est en pause. Reprenez-la dans la file audio."],
      ["error", "La préparation est interrompue. Ouvrez la file audio pour la reprendre."],
    ]) {
      for (const language of ["fr", "en", "es", "it", "de", "pt"]) {
        setLocale(language);
        document.body.innerHTML = audioControlsMarkup({ status: "buffering", prepared: true, preparationStatus: state });
        expect(document.querySelector(".voice-player-status").textContent).toBe(t(source));
        expect(document.querySelector('[data-voice-action="queue"]').textContent).toContain(t("Voir la file audio"));
        expect(document.querySelector('[data-voice-action="toggle"]').textContent).toContain(t("Pause"));
      }
    }
    document.body.innerHTML = audioControlsMarkup({ status: "paused", prepared: true, preparationStatus: "preparing" });
    expect(document.querySelector(".voice-player-status").textContent).toBe(t("Lecture vocale en pause"));
    expect(document.querySelector('[data-voice-action="queue"]')).toBeNull();
  });

  it("explains continuing preparation during listening without claiming a paused job is running", () => {
    document.body.innerHTML = audioControlsMarkup({ status: "playing", prepared: true, preparationStatus: "preparing" });
    expect(document.querySelector(".voice-player-status").textContent).toBe(t("La suite du livre se prépare pendant votre écoute."));
    document.body.innerHTML = audioControlsMarkup({ status: "playing", prepared: true, preparationStatus: "paused" });
    expect(document.querySelector(".voice-player-status").textContent).toBe("");
  });

  it("keeps placeholder parity and provides translated controls in six languages", () => {
    const placeholders = value => [...value.matchAll(/\{\w+\}/g)].map(([token]) => token).sort();
    for (const language of ["en", "es", "it", "de", "pt"]) {
      expect(Object.keys(translations[language])).toEqual(Object.keys(translations.en));
      for (const [source, translated] of Object.entries(translations[language])) {
        expect(translated.trim()).not.toBe("");
        expect(placeholders(translated)).toEqual(placeholders(source));
      }
    }
    for (const language of ["fr", "en", "es", "it", "de", "pt"]) {
      setLocale(language);
      document.body.innerHTML = audioQueueJobMarkup(makeJob("a", "ready"));
      expect(action("a", "remove").textContent).toContain(t("Supprimer l’audio"));
      expect(audioQueueErrorMessage({ code: "COORDINATION_UNAVAILABLE" })).toBe(t("Ce navigateur ne permet pas de préparer les livres en audio. Essayez un navigateur récent."));
    }
  });
});
