const rows = [
  ["Recherche officielle de Loyal Books, avec couvertures et lecture directe des EPUB.", "Search Loyal Books with its official search component, covers and direct EPUB reading.", "Busca en Loyal Books con su buscador oficial, portadas y lectura directa de EPUB.", "Cerca su Loyal Books con il motore ufficiale, copertine e lettura diretta degli EPUB.", "Loyal Books mit der offiziellen Suche, Covern und direktem EPUB-Lesen durchsuchen.", "Pesquise no Loyal Books com a pesquisa oficial, capas e leitura direta de EPUB."],
  ["Recherche Google · EPUB multilingues", "Google search · Multilingual EPUBs", "Búsqueda de Google · EPUB en varios idiomas", "Ricerca Google · EPUB multilingue", "Google-Suche · Mehrsprachige EPUBs", "Pesquisa Google · EPUB em vários idiomas"],
  ["Recherche Google sur Loyal Books", "Google search on Loyal Books", "Búsqueda de Google en Loyal Books", "Ricerca Google su Loyal Books", "Google-Suche auf Loyal Books", "Pesquisa Google no Loyal Books"],
  ["Saisissez un titre ou un auteur pour rechercher sur Loyal Books.", "Enter a title or author to search Loyal Books.", "Introduce un título o autor para buscar en Loyal Books.", "Inserisci un titolo o un autore per cercare su Loyal Books.", "Gib einen Titel oder Autor ein, um Loyal Books zu durchsuchen.", "Introduza um título ou autor para pesquisar no Loyal Books."],
  ["Chargement de la recherche Google…", "Loading Google search…", "Cargando la búsqueda de Google…", "Caricamento della ricerca Google…", "Google-Suche wird geladen…", "A carregar a pesquisa Google…"],
  ["Recherche sur Loyal Books…", "Searching Loyal Books…", "Buscando en Loyal Books…", "Ricerca su Loyal Books…", "Loyal Books wird durchsucht…", "A pesquisar no Loyal Books…"],
  ["La recherche Google sur Loyal Books est indisponible. Réessayez ou ouvrez le site source.", "Google search on Loyal Books is unavailable. Try again or open the source website.", "La búsqueda de Google en Loyal Books no está disponible. Inténtalo de nuevo o abre el sitio original.", "La ricerca Google su Loyal Books non è disponibile. Riprova o apri il sito originale.", "Die Google-Suche auf Loyal Books ist nicht verfügbar. Versuche es erneut oder öffne die Quellwebsite.", "A pesquisa Google no Loyal Books não está disponível. Tente novamente ou abra o site original."],
  ["Ouvrir Loyal Books", "Open Loyal Books", "Abrir Loyal Books", "Apri Loyal Books", "Loyal Books öffnen", "Abrir Loyal Books"],
  ["ce livre", "this book", "este libro", "questo libro", "dieses Buch", "este livro"],
  ["Titre ou auteur sur Loyal Books…", "Title or author on Loyal Books…", "Título o autor en Loyal Books…", "Titolo o autore su Loyal Books…", "Titel oder Autor auf Loyal Books…", "Título ou autor no Loyal Books…"],
  ["Recherchez un titre ou un auteur dans la barre en haut. La recherche Loyal Books inclut toutes les langues.", "Search for a title or author in the bar above. Loyal Books search includes all languages.", "Busca un título o autor en la barra superior. La búsqueda de Loyal Books incluye todos los idiomas.", "Cerca un titolo o un autore nella barra in alto. La ricerca di Loyal Books include tutte le lingue.", "Suche in der oberen Leiste nach einem Titel oder Autor. Die Suche auf Loyal Books umfasst alle Sprachen.", "Pesquise um título ou autor na barra superior. A pesquisa do Loyal Books inclui todos os idiomas."],
  ["Les résultats sont fournis par Google et peuvent inclure des annonces ou des pages sans EPUB. Le bouton Lire ouvre les fiches compatibles dans FastReader.", "Google provides these results, which may include ads or pages without an EPUB. Read opens compatible book pages in FastReader.", "Google proporciona los resultados, que pueden incluir anuncios o páginas sin EPUB. Leer abre las fichas compatibles en FastReader.", "I risultati sono forniti da Google e possono includere annunci o pagine senza EPUB. Leggi apre le schede compatibili in FastReader.", "Google liefert diese Ergebnisse, die Anzeigen oder Seiten ohne EPUB enthalten können. Lesen öffnet kompatible Buchseiten in FastReader.", "Os resultados são fornecidos pela Google e podem incluir anúncios ou páginas sem EPUB. Ler abre as fichas compatíveis no FastReader."],
  ["Ouvrir la recherche sur Loyal Books", "Open search on Loyal Books", "Abrir la búsqueda en Loyal Books", "Apri la ricerca su Loyal Books", "Suche auf Loyal Books öffnen", "Abrir a pesquisa no Loyal Books"],
  ["Cette recherche est transmise à Google. Vos EPUB, notes et repères restent dans votre navigateur.", "This search is sent to Google. Your EPUBs, notes and reading positions stay in your browser.", "Esta búsqueda se envía a Google. Tus EPUB, notas y posiciones de lectura permanecen en tu navegador.", "Questa ricerca viene inviata a Google. Gli EPUB, le note e i punti di lettura rimangono nel browser.", "Diese Suchanfrage wird an Google gesendet. Deine EPUBs, Notizen und Lesepositionen bleiben im Browser.", "Esta pesquisa é enviada à Google. Os seus EPUB, notas e posições de leitura ficam no navegador."],
  ["Confidentialité", "Privacy", "Privacidad", "Privacy", "Datenschutz", "Privacidade"],
  ["Impossible d’ouvrir ce livre pour le moment.", "This book cannot be opened right now.", "No se puede abrir este libro en este momento.", "Impossibile aprire questo libro al momento.", "Dieses Buch kann gerade nicht geöffnet werden.", "Não é possível abrir este livro de momento."],
];

export default Object.fromEntries(["en", "es", "it", "de", "pt"].map((locale, index) => [
  locale, Object.fromEntries(rows.map(([key, ...translations]) => [key, translations[index]])),
]));
