import { t, formatNumber } from "../i18n.js";
import { suggestionsMarkup } from "./suggestions.js";

export function homeMarkup(state, { icon, escape, cover }) {
  const recent = state.books.find(
    (book) => book.position && book.position.progress < 1,
  );
  const modes = `<div class="home-modes" aria-label="${t("Trois façons de lire")}"><div class="home-mode"><span class="home-mode-sample home-mode-rsvp" aria-hidden="true">${t("histoire")}</span><div><h2>${t("Mot à mot")}</h2><p>${t("Un mot à la fois, à la cadence que vous choisissez.")}</p></div></div><div class="home-mode"><span class="home-mode-sample home-mode-focus" aria-hidden="true">${t("<strong>His</strong>toire")}</span><div><h2>${t("Focus")}</h2><p>${t("Le début des mots accentué, selon votre préférence.")}</p></div></div><div class="home-mode"><span class="home-mode-sample home-mode-classic" aria-hidden="true">${t("Il était<br>une fois…")}</span><div><h2>${t("Classique")}</h2><p>${t("La page entière, pour avancer librement dans le texte.")}</p></div></div></div>`;
  return `<section class="home-intro" aria-labelledby="home-title"><div class="home-intro-copy"><span class="eyebrow">${t("LA LECTURE RAPIDE, À VOTRE RYTHME")}</span><h1 id="home-title">${t("Lisez plus vite.<br><em>Allez au bout de vos livres.</em>")}</h1><p>${t("Faites avancer votre pile à lire. Le mode Mot à mot affiche votre EPUB à la vitesse que vous choisissez. Ajustez la cadence, faites une pause et retrouvez le plaisir de finir un livre.")}</p><div class="home-actions"><button class="button ink" data-action="demo" ${state.busy ? "disabled" : ""}>${icon("play")} ${t("Essayer le lecteur")}</button><button class="button secondary" data-action="import" ${state.busy ? "disabled" : ""}>${icon("plus")} ${t("Importer un EPUB")}</button></div></div></section>
  ${recent ? `<section class="resume-card home-resume"><div class="resume-symbol">${icon("bookmark")}</div><div><span class="eyebrow">${t("REPRENDRE LE FIL")}</span><h2>${escape(recent.title)}</h2><p>${t("{progress} % parcouru · votre place est gardée", { progress: formatNumber(Math.round(recent.position.progress * 100)) })}</p></div><button class="button ink" data-action="open" data-id="${escape(recent.id)}">${icon("play")} ${t("Reprendre ma lecture")}</button></section>` : ""}
  ${suggestionsMarkup(state, { icon, escape, cover })}
  <details class="home-help"><summary>${t("Trois modes, comment commencer ?")} ${icon("plus")}</summary>${modes}<ol><li>${t("<strong>Choisissez un livre</strong> dans la sélection ou importez votre fichier EPUB.")}</li><li>${t("<strong>Essayez les trois modes</strong> et adaptez le texte dans les réglages de lecture.")}</li><li>${t("<strong>Reprenez quand vous voulez.</strong> Vos livres importés, notes et repères restent sur cet appareil, sans compte.")}</li></ol><p>${t("Les livres enregistrés se lisent aussi hors connexion une fois l’application disponible hors ligne.")}</p></details>`;
}
