import { suggestionsMarkup } from "./suggestions.js";

export function homeMarkup(state, { icon, escape, cover }) {
  const recent = state.books.find(
    (book) => book.position && book.position.progress < 1,
  );
  const modes = `<div class="home-modes" aria-label="Trois façons de lire"><div class="home-mode"><span class="home-mode-sample home-mode-rsvp" aria-hidden="true">histoire</span><div><h2>Mot à mot</h2><p>Un mot à la fois, à la cadence que vous choisissez.</p></div></div><div class="home-mode"><span class="home-mode-sample home-mode-classic" aria-hidden="true">Il était<br>une fois…</span><div><h2>Classique</h2><p>La page entière, pour avancer librement dans le texte.</p></div></div><div class="home-mode"><span class="home-mode-sample home-mode-focus" aria-hidden="true"><strong>His</strong>toire</span><div><h2>Focus</h2><p>Le début des mots accentué, selon votre préférence.</p></div></div></div>`;
  return `<section class="home-intro" aria-labelledby="home-title"><div class="home-intro-copy"><span class="eyebrow">UN LIVRE, UN MOMENT POUR VOUS</span><h1 id="home-title">Ouvrez un livre.<br><em>Trouvez votre rythme.</em></h1><p>Des histoires à découvrir, trois façons de les lire. Retrouvez vos livres et votre place sur cet appareil.</p><div class="home-actions"><button class="button ink" data-action="demo" ${state.busy ? "disabled" : ""}>${icon("play")} Essayer le lecteur</button><button class="button secondary" data-action="import" ${state.busy ? "disabled" : ""}>${icon("plus")} Importer un EPUB</button></div></div></section>
  ${recent ? `<section class="resume-card home-resume"><div class="resume-symbol">${icon("bookmark")}</div><div><span class="eyebrow">REPRENDRE LE FIL</span><h2>${escape(recent.title)}</h2><p>${Math.round(recent.position.progress * 100)} % parcouru · votre place est gardée</p></div><button class="button ink" data-action="open" data-id="${escape(recent.id)}">${icon("play")} Reprendre ma lecture</button></section>` : ""}
  ${suggestionsMarkup(state, { icon, escape, cover })}
  <details class="home-help"><summary>Trois modes, comment commencer ? ${icon("plus")}</summary>${modes}<ol><li><strong>Choisissez un livre</strong> dans la sélection ou importez votre fichier EPUB.</li><li><strong>Essayez les trois modes</strong> et adaptez le texte dans les réglages de lecture.</li><li><strong>Reprenez quand vous voulez.</strong> Vos livres importés, notes et repères restent sur cet appareil, sans compte.</li></ol><p>Les livres enregistrés se lisent aussi hors connexion une fois l’application disponible hors ligne.</p></details>`;
}
