import { t, formatNumber } from "../i18n.js";
export function libraryMarkup(state, { icon, escape, cover }) {
  const recent = state.books.find(
    (book) => book.position && book.position.progress < 1,
  );
  const shown = state.books;
  return `<section class="library-intro"><div><span class="eyebrow">${t("VOTRE ESPACE DE LECTURE")}</span><h1>${t("Ma bibliothèque")}</h1><p>${state.books.length ? t("Vos livres, vos notes, votre rythme. Tout reste sur cet appareil.") : t("Votre bibliothèque attend ses premiers livres. Importez un EPUB ou choisissez un titre dans Découvrir.")}</p></div><a class="button ink" href="#discover">${icon("compass")} ${t("Trouver un livre")}</a></section>
  ${recent ? `<section class="resume-card"><div class="resume-symbol">${icon("bookmark")}</div><div><span class="eyebrow">${t("REPRENDRE LE FIL")}</span><h2>${escape(recent.title)}</h2><p>${t("{progress} % parcouru · votre place est gardée", { progress: formatNumber(Math.round(recent.position.progress * 100)) })}</p></div><button class="button ink" data-action="open" data-id="${escape(recent.id)}">${icon("play")} ${t("Reprendre ma lecture")}</button></section>` : ""}
  <section class="library-section"><div class="section-heading"><h2>${t("Mes livres")} <span class="count-pill">${formatNumber(state.books.length)}</span></h2><button class="button secondary library-backup-button" data-action="backup" aria-label="${t("Sauvegarde et stockage")}">${icon("archive")} ${t("Sauvegarde")}</button></div>
  <div class="book-grid">${shown.map((book, index) => `<article class="book-card"><button class="book-open" data-action="open" data-id="${escape(book.id)}" aria-label="${t("Lire {title}", { title: escape(book.title) })}">${cover(book, index)}<h3>${escape(book.title)}</h3><p>${escape(book.author)}</p></button><div class="book-card-meta"><span>${book.position ? t("{progress} % lu", { progress: formatNumber(Math.round(book.position.progress * 100)) }) : t("Prêt à lire")}</span><button class="remove-button" data-action="remove" data-id="${escape(book.id)}" aria-label="${t("Supprimer {title}", { title: escape(book.title) })}" title="${t("Supprimer de cet appareil")}">${icon("close")}</button></div><progress max="1" value="${book.position?.progress || 0}" aria-label="${t("Progression de {title}", { title: escape(book.title) })}"></progress><button class="book-export book-download" data-action="library-export" data-id="${escape(book.id)}" aria-label="${t("Télécharger en Classique : {title}", { title: escape(book.title) })}" ${state.busy ? "disabled" : ""}>${icon("download")} ${t("Télécharger l’EPUB")}</button></article>`).join("")}
  <button class="import-card" data-action="import" ${state.busy ? "disabled" : ""}><span class="import-circle">${icon("plus")}</span><strong>${state.busy ? t("Ouverture en cours…") : t("Importer un EPUB")}</strong><span>${t("Depuis les fichiers<br>de votre appareil")}</span><span class="file-label">${t("30 Mo maximum")}</span></button></div>
  ${!state.books.length ? `<div class="library-start"><p>${t("Besoin d’inspiration ?")}</p><a class="button secondary" href="#home">${icon("compass")} ${t("Voir les suggestions")}</a></div>` : ""}</section>`;
}
