export function readerMarkup(state, { icon, escape, applyFocus }) {
  const { book, position, settings } = state;
  const chapter = book.chapters[position.chapterIndex];
  const modes = [
    ["classic", "Classique"],
    ["focus", "Focus"],
    ["rsvp", "Mot à mot"],
  ];
  const marks = position.bookmarks || [];
  const notes = position.annotations || [];
  const panelHeading = (title, action) =>
    `<div class="settings-heading"><h2>${title}</h2><button class="round-button" data-action="${action}" aria-label="Fermer ${action === "settings" ? "les réglages" : "mes repères"}">${icon("close")}</button></div>`;
  return `<div class="reader-shell" data-reading-mode="${settings.mode}">
    <header class="reader-header"><a href="#library" class="reader-back" aria-label="Retour à ma bibliothèque">${icon("back")}<span>Bibliothèque</span></a><div class="reader-title"><strong>${escape(book.title)}</strong><span>${escape(book.author)}</span></div><div class="reader-tools"><button class="round-button" data-action="bookmark" aria-label="Ajouter un signet" title="Marquer cette page">${icon("bookmark")}</button><button class="round-button ${state.settingsOpen ? "selected" : ""}" data-action="settings" aria-label="Réglages de lecture" aria-expanded="${state.settingsOpen}" aria-controls="reader-settings">${icon("settings")}</button></div></header>
    <div class="reader-modebar"><div class="reading-modes" role="group" aria-label="Choisir le mode de lecture">${modes.map(([id, label]) => `<button data-action="reading-mode" data-mode="${id}" aria-pressed="${settings.mode === id}">${label}</button>`).join("")}</div><span class="reader-mode-description">${settings.mode === "rsvp" ? "Un mot à la fois. Vous donnez le rythme." : settings.mode === "focus" ? "Le début des mots en évidence." : "Le texte entier, à votre rythme."}</span></div>
    <div class="reader-layout"><main id="main" tabindex="-1" class="reading-main">
    <div class="chapter-heading"><div class="chapter-heading-top"><span id="chapter-label" class="eyebrow">CHAPITRE ${position.chapterIndex + 1} SUR ${book.chapters.length}</span><span class="place-saved">${icon("bookmark")}<span id="save-status">Votre place est gardée</span></span></div><h1>${escape(chapter.title)}</h1><div class="chapter-details"><span>${Math.max(1, Math.ceil(chapter.wordCount / settings.speed))} min estimées</span><span id="screen-position"></span></div></div>
    <div id="chapter-scroll" class="chapter-scroll" tabindex="0" aria-label="Texte du chapitre" ${settings.mode === "rsvp" ? "hidden" : ""}><article id="chapter-content" class="chapter-content" lang="${escape(book.language || "fr")}">${applyFocus(chapter.html, settings.mode === "focus")}</article><div class="chapter-end"><span>Votre progression est enregistrée sur cet appareil.</span><button class="button secondary" data-action="next-chapter">${position.chapterIndex === book.chapters.length - 1 ? "Terminer le livre" : "Chapitre suivant"} ${icon("arrow")}</button></div></div>
    <div id="rsvp" class="rsvp" ${settings.mode !== "rsvp" ? "hidden" : ""}><div class="rsvp-stage" aria-label="Mot en cours de lecture"><span id="rsvp-word"></span></div><div class="rsvp-controls"><button class="round-button" data-action="rewind" aria-label="Reculer de dix mots">${icon("back")}</button><button id="play-button" class="button ink" data-action="play">${icon("play")} Démarrer</button><button class="round-button" data-action="forward" aria-label="Avancer de dix mots">${icon("arrow")}</button></div><p id="rsvp-count" class="subtle"></p><div class="rsvp-context"><p id="rsvp-context-text"></p><button class="text-link" data-action="show-context">${icon("book")} Voir le passage complet</button></div><p class="rsvp-help">Touchez Pause pour souffler. <span class="keyboard-help">Sur clavier : touche Espace.</span></p></div>
    <div id="selection-toolbar" class="selection-toolbar" role="toolbar" aria-label="Actions sur le passage sélectionné" hidden><span>Ce passage vous parle ?</span><button class="button ink" data-action="highlight">Surligner</button><button class="button secondary" data-action="annotate">Ajouter une note</button><button class="round-button" data-action="clear-selection" aria-label="Fermer la sélection">${icon("close")}</button></div>
    </main>
    <aside id="reader-settings" class="reader-settings" ${state.settingsOpen ? "" : "hidden"}>${panelHeading("Réglages de lecture", "settings")}
    <label class="setting-label" for="chapter-select">Chapitres</label><select id="chapter-select">${book.chapters.map((item, index) => `<option value="${index}" ${index === position.chapterIndex ? "selected" : ""}>${index + 1}. ${escape(item.title)}</option>`).join("")}</select>
    <fieldset><legend>Mode de lecture</legend><div class="mode-options">${[
      ["classic", "Classique", "La page, tout simplement"],
      ["focus", "Focus", "Le début des mots en évidence"],
      ["rsvp", "Mot à mot", "Un mot à la fois, à votre vitesse"],
    ]
      .map(
        ([id, label, description]) =>
          `<label class="mode-option"><input type="radio" name="mode" value="${id}" ${settings.mode === id ? "checked" : ""}><span><strong>${label}</strong><small>${description}</small></span></label>`,
      )
      .join("")}</div></fieldset>
    <fieldset><legend>Couleurs du site et du lecteur</legend><div class="theme-options">${[
      ["paper", "Clair"],
      ["sepia", "Sépia"],
      ["night", "Sombre"],
    ]
      .map(
        ([id, label]) =>
          `<button class="theme-choice theme-${id}" data-action="theme" data-theme="${id}" aria-pressed="${settings.theme === id}">${label}</button>`,
      )
      .join("")}</div></fieldset>
    <label class="setting-label" for="font-size">Taille du texte <output id="font-size-value">${settings.fontSize} px</output></label><input id="font-size" type="range" min="16" max="32" step="1" value="${settings.fontSize}" />
    <label class="setting-label" for="font-family">Police</label><select id="font-family"><option value="serif" ${settings.font === "serif" ? "selected" : ""}>Littéraire · Georgia</option><option value="sans" ${settings.font === "sans" ? "selected" : ""}>Épurée · Sans serif</option></select>
    <label class="setting-label" for="reading-speed">Vitesse <output id="speed-value">${settings.speed} mots/min</output></label><input id="reading-speed" type="range" min="100" max="800" step="25" value="${settings.speed}" /><p class="setting-hint">La cadence règle le mode mot à mot et les estimations. Ralentissez ou retrouvez la page dès que vous en avez besoin.</p>
    ${book.source?.rightsUrl ? `<p class="source-rights"><a href="${escape(book.source.rightsUrl)}" target="_blank" rel="noopener noreferrer">Source et droits de ce livre ${icon("external")}</a></p>` : ""}
    ${book.original ? `<button class="button secondary export-button" data-action="export-original" ${state.busy ? "disabled" : ""}>${icon("download")} Télécharger l’EPUB original</button><button class="button secondary export-button" data-action="export" ${state.busy ? "disabled" : ""}>${icon("download")} Exporter l’EPUB Focus</button>` : ""}<p class="device-note">Votre position suit le passage du texte, même quand vous changez la taille des caractères.</p></aside>
    <aside id="reader-notes" class="reader-settings reader-notes" ${state.notesOpen ? "" : "hidden"}>${panelHeading("Mes repères", "notes")}
      <div class="automatic-bookmark"><span class="ribbon">${icon("bookmark")}</span><span class="eyebrow">VOTRE MARQUE-PAGE AUTOMATIQUE</span><h3>${escape(chapter.title)}</h3><p id="auto-bookmark-quote">${escape(position.locator?.exact || "Votre position se sauvegarde pendant la lecture.")}</p><span class="setting-hint">Vous retrouverez ce passage à la prochaine ouverture.</span></div>
      <section class="passage-search-section"><form id="passage-search"><label for="passage-query">Retrouver un passage</label><div><input id="passage-query" name="passage" type="search" placeholder="Quelques mots du livre…" minlength="2" maxlength="120" required value="${escape(state.passageQuery)}"><button class="round-button" aria-label="Chercher dans le livre">${icon("search")}</button></div></form><div class="passage-results" tabindex="-1" aria-live="polite">${state.passageSearched ? `<p class="setting-hint">${state.passageResults.length ? `${state.passageResults.length === 20 ? "Les 20 premiers" : state.passageResults.length} passages trouvés` : "Aucun passage trouvé. Essayez d’autres mots."}</p>${state.passageResults.map((result, index) => `<button class="passage-result" data-action="goto-passage" data-index="${index}"><span>${escape(result.chapterTitle)}</span><q>${escape(result.quote)}</q></button>`).join("")}` : ""}</div></section>
      <div class="notes-section-heading"><h3>Pages marquées <span>${marks.length}</span></h3><button class="round-button" data-action="bookmark" aria-label="Marquer le passage actuel">${icon("plus")}</button></div>
      <div class="bookmark-list">${marks.length ? marks.map((mark, index) => `<div class="bookmark-row bookmark-card"><button class="bookmark-jump" data-action="goto-bookmark" data-index="${index}"><span>${icon("bookmark")} ${escape(book.chapters[mark.chapterIndex]?.title || "Chapitre")}</span><q>${escape(mark.locator?.exact || `À ${Math.round(mark.scrollRatio * 100)} % du chapitre`)}</q></button><button class="bookmark-delete" data-action="remove-bookmark" data-index="${index}" aria-label="Supprimer le signet ${index + 1}">${icon("close")}</button></div>`).join("") : '<p class="setting-hint">Touchez le ruban en haut du lecteur pour garder un passage.</p>'}</div>
      <div class="notes-section-heading"><h3>Passages et notes <span>${notes.length}</span></h3></div>
      <div class="annotation-list">${notes.length ? notes.map((note, index) => `<article class="annotation-card"><button class="annotation-jump" data-action="goto-note" data-index="${index}"><span class="eyebrow">${escape(book.chapters[note.chapterIndex]?.title || "Chapitre")}</span><blockquote>${escape(note.quote)}</blockquote></button>${note.note ? `<p>${escape(note.note)}</p>` : ""}<div><button class="text-link" data-action="edit-note" data-index="${index}">Modifier la note</button><button class="round-button" data-action="remove-note" data-index="${index}" aria-label="Supprimer le passage ${index + 1}">${icon("close")}</button></div></article>`).join("") : '<p class="setting-hint">Sélectionnez du texte pour le surligner ou lui ajouter une note.</p>'}</div>
      <button class="button secondary export-button" data-action="export-notes" ${!marks.length && !notes.length ? "disabled" : ""}>${icon("download")} Exporter mes repères</button><p class="device-note">Vos repères et vos livres sont enregistrés dans ce navigateur, sur cet appareil.</p>
    </aside></div>
    <footer class="reader-footer reader-control-panel"><div class="reader-commandbar"><div class="quick-pace" ${settings.mode === "rsvp" ? "" : "hidden"}><button data-action="speed-down" aria-label="Ralentir de 25 mots par minute">−</button><div class="pace-value"><output id="quick-speed">${settings.speed}</output><span>mots/min</span></div><button data-action="speed-up" aria-label="Accélérer de 25 mots par minute">+</button></div><button class="notes-toggle ${state.notesOpen ? "selected" : ""}" data-action="notes" aria-controls="reader-notes" aria-expanded="${state.notesOpen}">${icon("bookmark")}<span>Mes repères</span>${marks.length + notes.length ? `<span class="count-pill">${marks.length + notes.length}</span>` : ""}</button></div>
    <div class="reader-navigation"><button class="round-button" data-action="previous-chapter" aria-label="Chapitre précédent" ${position.chapterIndex === 0 ? "disabled" : ""}>${icon("back")}</button><div class="reading-progress"><div><span id="progress-label"></span><span id="remaining-label"></span></div><progress id="book-progress" max="1" value="${position.progress}" aria-label="Progression du livre"></progress></div><button class="round-button" data-action="next-chapter" aria-label="${position.chapterIndex === book.chapters.length - 1 ? "Terminer le livre" : "Chapitre suivant"}">${icon("arrow")}</button></div></footer></div>`;
}
